server:
  port: 8080
  
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://localhost:3306/trip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&allowMultiQueries=true
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      pool-name: ConnPool
  servlet:
    multipart:
      max-file-size: 25MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: '{adminId}'
    password: '{adminPw}'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.trip.*.model
  
logging:
  level:
    root: info
    com.trip: debug
